name: Manually Update Data

on: workflow_dispatch

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run JavaScript script
        env:
            API_URL: ${{ secrets.API_URL }}
            API_PRIVATE_KEY: ${{ secrets.API_PRIVATE_KEY }}
            API_PUBLIC_KEY: ${{ secrets.API_PUBLIC_KEY }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          node index.js

      - name: Commit and push changes
        run: |
          if [[ -n "$(git diff --exit-code)" ]]; then
            echo "Changes detected. Updating data."
            git config user.email "${{ github.actor }}@users.noreply.github.com"
            git config user.name "Scheduled Job"
            git add docs/data.json
            git add docs/meta.json
            git commit -m "Update data"
            git push
          else
            echo "No changes detected"
          fi
